# CLOSE ISSUE BOT
# ---------------
# A bot which helps you to close issues that don't include some specific contents.
# See how to use it in https://github.com/offu/close-issue-app.

# Comment that will be sent if an issue is judged to be closed.
comment: >-
  This issue has been automatically closed because the issue template is missing or incomplete.
  Filling the template is required so standard questions don't need to be asked again each time.
  Our ability to provide assistance is greatly hampered if few minutes are not taken to complete the issue template
  with the requested information. The details requested potentially affect which options to pursue. The small amount
  of time you will spend completing the template will also help the volunteers, providing assistance to you, to reduce
  the time required to help you.
issueConfigs:
# There can be several configs for different kind of issues.
- content:
# template 1: bug report
  - "Example file"
  - "Log"
  - "To Reproduce"
  - "Version"
# - content:
# template 2: feature request
  # - "Have you looked for this feature in other issues and in the docs"
  # - "Describe the solution you'd like"

# Optional configuration:
#
# whether the keywords are case-insensitive
# default value is false, which means keywords are case-sensitive
caseInsensitive: true
# the label that will be added when the bot close an issue
# The bot will only add a label if this property is set.
label: "template missing/incomplete"
# The issue is judged to be legal if it includes all keywords from any of these two configs.
# Or it will be closed by the app.
